### PR TITLE
fix(Broken links in API documentation to packages #477): remove html …

### LINKED ISSUE #477: Broken links in API documentation to packages
**Describe the bug**
As mentioned in the Slack channel ([thread](https://druxtjs.org/api/packages/menu/menu.html)), several links in the API documention of packages are broken.

@Decipher replied
_The pages are generated from jsdoc and Vue-docgen, so the link will be the result of a bad link in the source code. It’s just a matter odd chasing the bad links and regenerating the site._
https://github.com/druxt/druxt.js/blob/5bdf61c55c09e0a830daf2fe7a6766ed77b6419b/packages/menu/src/index.js#L11

**To Reproduce**
1. Go to https://druxtjs.org/api/packages/menu/#module_DruxtMenu
2. Click on **See: [DruxtMenu](https://druxtjs.org/api/packages/menu/menu.html)**
3. See error 'Document not found'

**Expected behavior**
The correct link is without the .html extionsion, so https://druxtjs.org/api/packages/menu/menu works.

### PR DESCRIPTION
**Pull request by Sebastix**
## Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Removes all html extensions in the jsdocs to fix some broken links in the API packages documentation.
Resolves #477 

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] I have added tests to cover my changes (if not applicable, please state why)
- [x] All new and existing tests are passing.

<a href="https://gitpod.io/#https://github.com/druxt/druxt.js/pull/478"></a>

### CODE REVIEW

File: packages/blocks/src/components/blocks/DruxtBlockBlockContent.vue [hunk 1]
```diff
@@ -52,7 +52,7 @@ export default {
      *
      * @type {object}
      *
-     * @see {@link https://druxt.github.io/druxt-entity/api/components/DruxtEntity.html|DruxtEntity}
```
Comment (Decipher) [inline packages/blocks/src/components/blocks/DruxtBlockBlockContent.vue:55]: These absolute URLs no longer exist and will need to be updated to relative links, however I can update them after I merge this in.

**Review by Decipher — APPROVED** [review]

**Comment by Decipher** [comment]
Thanks @Sebastix, this is great.

I have tested and confirmed that this works as expected, and will get the website update soon.
